name: Docker Compose Actions Workflow
on: push
jobs:
  setup-vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest
      - name: Install dependencies, import the module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, PoshRSJob -ErrorAction Stop
          Import-Module ./acastools.psd1 -ErrorAction Stop
      - name: Test the port and accept self-signed cert
        run: curl -s --retry 10 --retry-connrefused https://localhost:8834/ --insecure
      - name: Execute commands inside container
        run: |
          docker exec nessus bash -c 'ls -la'
          docker exec nessus bash -c 'hostname'
