name: Actions Workflow
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # setup and run docker container
      - name: Download the container
        run: docker pull sometheycallme/docker-nessus:latest
      # separate download and run just to see the timing
      - name: Startup the container
        run: docker run -p 8834:8834 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest

      # setup nessus
      - name: Sleep to give nessus time to startup
        run: sleep 20
      - name: Test the port and accept self-signed cert
        run: |
          curl -s --retry 10 --retry-connrefused https://localhost:8834 --insecure > /dev/null
      - name: Write nessus license
        run: 'echo "$NLICENSE" > /tmp/nessus.license'
        shell: bash
        env:
          NLICENSE: ${{secrets.LICENSE}}

      # setup powershell
      - name: Setup PowerShell module cache
        id: cache-psmodulesupdate
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.local/share/powershell/Modules/PSFramework
            /home/runner/.local/share/powershell/Modules/Pester
          key: ${{ runner.os }}-psmodulesupdate
      - name: Install required PowerShell modules
        if: steps.cache-psmodulesupdate.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSFramework, Pester -ErrorAction Stop
      - name: Import tentools and test connect to the container
        shell: pwsh
        run: |
          $cred = New-Object -TypeName PSCredential -ArgumentList "admin", (ConvertTo-SecureString -String admin123 -AsPlainText -Force)
          Import-Module ./tentools.psd1
          $splat = @{
            ComputerName = "localhost"
            AcceptSelfSignedCert = $true
            Credential = $cred
            EnableException = $true
            Port = 8834
            Path = "/tmp/nessus.license"
          }
          Initialize-TenServer @splat
