name: Actions Workflow
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup docker image
      - name: Download the image if required
        run: docker pull sometheycallme/docker-nessus:latest
      - name: Startup the container
        run: docker run -p 8834:8834 -p 2220:22 --hostname nessus --name nessus -d sometheycallme/docker-nessus:latest

      # setup nessus
      - name: Write nessus license from secrets to disk
        run: 'echo "$NLICENSE" > /tmp/nessus.license'
        shell: bash
        env:
          NLICENSE: ${{secrets.LICENSE}}

      # setup CA certificate trust to emulate prod
      - name: Write CA Cert
        run: 'echo "$CACERT" > /tmp/cacert.pem'
        shell: bash
        env:
          CACERT: ${{secrets.CACERT}}
      - name: Trust the CA
        run: |
          sudo cp /tmp/cacert.pem /etc/ssl/certs/ca.crt
          sudo chmod 644 /etc/ssl/certs/ca.crt
          sudo update-ca-certificates

      # setup cert in container to emulate prod
      - name: Write SSL Key
        run: 'echo "$SSLKEY" > /tmp/serverkey.pem'
        shell: bash
        env:
          SSLKEY: ${{secrets.SSLKEY}}
      - name: Write SSL Cert
        run: 'echo "$SSLCERT" > /tmp/servercert.pem'
        shell: bash
        env:
          SSLCERT: ${{secrets.SSLCERT}}
      - name: Copy certs to docker
        run: |
          docker cp /tmp/serverkey.pem nessus:/opt/nessus/var/nessus/CA/serverkey.pem
          docker cp /tmp/servercert.pem nessus:/opt/nessus/com/nessus/CA/servercert.pem

      - name: Download plugins
        run: 'wget "$TGZ" -O /tmp/all-2.0.tar.gz -q'
        shell: bash
        env:
          TGZ: ${{secrets.TGZ}}
      - name: Copy tgz to docker
        run: |
          docker cp /tmp/all-2.0.tar.gz nessus:/tmp/all-2.0.tar.gz

      # time to party
      - name: Set required PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v1
        with:
          modules-to-cache: PSFramework, PoshRSJob
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}
      - name: Install required PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ${{ steps.psmodulecache.outputs.needed }} -ErrorAction Stop
      - name: Initialize the nessus server with admin user and license
        shell: pwsh
        run: |
          Import-Module ./tentools.psd1
          Wait-TenServerReady -ComputerName localhost -Register
          $cred = New-Object -TypeName PSCredential -ArgumentList "admin", (ConvertTo-SecureString -String admin123 -AsPlainText -Force)
          $splat = @{
            ComputerName = "localhost"
            AcceptSelfSignedCert = $false
            Credential = $cred
            EnableException = $true
            Port = 8834
            Path = "/tmp/nessus.license"
          }
          Initialize-TenServer @splat
      - name: Run Pester tests
        shell: pwsh
        run: |
          ./tests/pester.ps1
